FROM alpine:latest

RUN apk add --no-cache \
    wget \
    unzip \
    ca-certificates \
    && wget https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip \
    && unzip duckdb_cli-linux-amd64.zip -d /usr/local/bin \
    && rm duckdb_cli-linux-amd64.zip \
    && chmod +x /usr/local/bin/duckdb \
    && apk del wget unzip

WORKDIR /data/duckdb

CMD ["sh", "-c", "tail -f /dev/null"]
